### PR TITLE
fixed issue "Academics drop-down issue"

### PR DESCRIPTION
**Pull request by mahak5**

### CODE REVIEW

**Comment by shivhek25** [comment]
Can you attach a screenshot of the fixed issue ? Please run the file in Chrome in full screen.

**Comment by mahak5** [comment]
capture

**Comment by shivhek25** [comment]
Can you see there's reduced space between the logo and the "home" tab ? That shouldn't be there. Can you fix that and then commit again ?

**Comment by mahak5** [comment]
capture1 done!

**Comment by shivhek25** [comment]
Perfect !

**Pull request merged**
